// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnhlfqardmpyoigqaprg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuaGxmcWFyZG1weW9pZ3FhcHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTk3MDcsImV4cCI6MjA1ODA3NTcwN30.xF9RqhDZjQp0tHAK2glQNtkgJ6kUksieo2qP6WXG7Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);